// Coordenadas das regiões clicáveis em porcentagem
// Baseado em vistas frontal e posterior do paciente

export interface RegiaoVisualMI {
  id: string
  label: string
  vista: 'frontal' | 'posterior' | 'plantar'
  x: number // porcentagem desde esquerda
  y: number // porcentagem desde topo
  width: number // largura em porcentagem
  height: number // altura em porcentagem
}

// ===== VISTA FRONTAL =====
export const REGIOES_FRONTAIS_MEMBROS_INFERIORES: RegiaoVisualMI[] = [
  {
    id: 'frontal_coxa_direita',
    label: 'Coxa direita',
    vista: 'frontal',
    x: 24,
    y: 4,
    width: 20,
    height: 31,
  },
  {
    id: 'frontal_coxa_esquerda',
    label: 'Coxa esquerda',
    vista: 'frontal',
    x: 56,
    y: 4,
    width: 20,
    height: 31,
  },
  {
    id: 'frontal_joelho_direito',
    label: 'Joelho direito',
    vista: 'frontal',
    x: 25,
    y: 34,
    width: 19,
    height: 12,
  },
  {
    id: 'frontal_joelho_esquerdo',
    label: 'Joelho esquerdo',
    vista: 'frontal',
    x: 56,
    y: 34,
    width: 19,
    height: 12,
  },
  {
    id: 'frontal_perna_direita',
    label: 'Perna direita',
    vista: 'frontal',
    x: 26,
    y: 45,
    width: 20,
    height: 26,
  },
  {
    id: 'frontal_perna_esquerda',
    label: 'Perna esquerda',
    vista: 'frontal',
    x: 54,
    y: 45,
    width: 20,
    height: 26,
  },
  {
    id: 'frontal_tornozelo_direito',
    label: 'Tornozelo direito',
    vista: 'frontal',
    x: 27,
    y: 70,
    width: 19,
    height: 10,
  },
  {
    id: 'frontal_tornozelo_esquerdo',
    label: 'Tornozelo esquerdo',
    vista: 'frontal',
    x: 54,
    y: 70,
    width: 19,
    height: 10,
  },
  {
    id: 'frontal_maleolo_medial_direito',
    label: 'Maléolo medial direito',
    vista: 'frontal',
    x: 39,
    y: 73,
    width: 8,
    height: 8,
  },
  {
    id: 'frontal_maleolo_medial_esquerdo',
    label: 'Maléolo medial esquerdo',
    vista: 'frontal',
    x: 53,
    y: 73,
    width: 8,
    height: 8,
  },
  {
    id: 'frontal_dorso_pe_direito',
    label: 'Dorso do pé direito',
    vista: 'frontal',
    x: 13,
    y: 79,
    width: 33,
    height: 14,
  },
  {
    id: 'frontal_dorso_pe_esquerdo',
    label: 'Dorso do pé esquerdo',
    vista: 'frontal',
    x: 54,
    y: 79,
    width: 33,
    height: 14,
  },
  {
    id: 'frontal_halux_direito',
    label: 'Hálux direito',
    vista: 'frontal',
    x: 36,
    y: 88,
    width: 10,
    height: 9,
  },
  {
    id: 'frontal_halux_esquerdo',
    label: 'Hálux esquerdo',
    vista: 'frontal',
    x: 54,
    y: 88,
    width: 10,
    height: 9,
  },
  {
    id: 'frontal_trajeto_venoso_superficial_direito',
    label: 'Trajeto venoso superficial direito',
    vista: 'frontal',
    x: 19,
    y: 18,
    width: 8,
    height: 54,
  },
  {
    id: 'frontal_trajeto_venoso_superficial_esquerdo',
    label: 'Trajeto venoso superficial esquerdo',
    vista: 'frontal',
    x: 73,
    y: 18,
    width: 8,
    height: 54,
  },
]

// ===== VISTA POSTERIOR =====
export const REGIOES_POSTERIORES_MEMBROS_INFERIORES: RegiaoVisualMI[] = [
  {
    id: 'posterior_coxa_direita',
    label: 'Coxa direita posterior',
    vista: 'posterior',
    x: 24,
    y: 4,
    width: 20,
    height: 31,
  },
  {
    id: 'posterior_coxa_esquerda',
    label: 'Coxa esquerda posterior',
    vista: 'posterior',
    x: 56,
    y: 4,
    width: 20,
    height: 31,
  },
  {
    id: 'posterior_fossa_poplitea_direita',
    label: 'Fossa poplítea direita',
    vista: 'posterior',
    x: 25,
    y: 34,
    width: 19,
    height: 12,
  },
  {
    id: 'posterior_fossa_poplitea_esquerda',
    label: 'Fossa poplítea esquerda',
    vista: 'posterior',
    x: 56,
    y: 34,
    width: 19,
    height: 12,
  },
  {
    id: 'posterior_panturrilha_direita',
    label: 'Panturrilha direita',
    vista: 'posterior',
    x: 25,
    y: 44,
    width: 21,
    height: 28,
  },
  {
    id: 'posterior_panturrilha_esquerda',
    label: 'Panturrilha esquerda',
    vista: 'posterior',
    x: 54,
    y: 44,
    width: 21,
    height: 28,
  },
  {
    id: 'posterior_tendao_calcaneo_direito',
    label: 'Tendão calcâneo direito',
    vista: 'posterior',
    x: 32,
    y: 68,
    width: 9,
    height: 14,
  },
  {
    id: 'posterior_tendao_calcaneo_esquerdo',
    label: 'Tendão calcâneo esquerdo',
    vista: 'posterior',
    x: 59,
    y: 68,
    width: 9,
    height: 14,
  },
  {
    id: 'posterior_tornozelo_direito',
    label: 'Tornozelo direito posterior',
    vista: 'posterior',
    x: 27,
    y: 71,
    width: 18,
    height: 10,
  },
  {
    id: 'posterior_tornozelo_esquerdo',
    label: 'Tornozelo esquerdo posterior',
    vista: 'posterior',
    x: 55,
    y: 71,
    width: 18,
    height: 10,
  },
  {
    id: 'posterior_calcaneo_direito',
    label: 'Calcâneo direito',
    vista: 'posterior',
    x: 27,
    y: 79,
    width: 19,
    height: 13,
  },
  {
    id: 'posterior_calcaneo_esquerdo',
    label: 'Calcâneo esquerdo',
    vista: 'posterior',
    x: 55,
    y: 79,
    width: 19,
    height: 13,
  },
  {
    id: 'posterior_planta_pe_direito',
    label: 'Base plantar direita',
    vista: 'posterior',
    x: 18,
    y: 88,
    width: 28,
    height: 10,
  },
  {
    id: 'posterior_planta_pe_esquerdo',
    label: 'Base plantar esquerda',
    vista: 'posterior',
    x: 55,
    y: 88,
    width: 28,
    height: 10,
  },
  {
    id: 'posterior_trajeto_venoso_superficial_direito',
    label: 'Trajeto venoso superficial posterior direito',
    vista: 'posterior',
    x: 20,
    y: 18,
    width: 8,
    height: 54,
  },
  {
    id: 'posterior_trajeto_venoso_superficial_esquerdo',
    label: 'Trajeto venoso superficial posterior esquerdo',
    vista: 'posterior',
    x: 72,
    y: 18,
    width: 8,
    height: 54,
  },
]

// ===== VISTA BASE PLANTAR =====
export const REGIOES_BASE_PLANTAR_MEMBROS_INFERIORES: RegiaoVisualMI[] = [
  {
    id: 'plantar_pe_direito',
    label: 'Planta do pé direito',
    vista: 'plantar',
    x: 15,
    y: 35,
    width: 32,
    height: 52,
  },
  {
    id: 'plantar_pe_esquerdo',
    label: 'Planta do pé esquerdo',
    vista: 'plantar',
    x: 53,
    y: 35,
    width: 32,
    height: 52,
  },
  {
    id: 'plantar_calcaneo_direito',
    label: 'Calcâneo direito',
    vista: 'plantar',
    x: 18,
    y: 29,
    width: 26,
    height: 20,
  },
  {
    id: 'plantar_calcaneo_esquerdo',
    label: 'Calcâneo esquerdo',
    vista: 'plantar',
    x: 56,
    y: 29,
    width: 26,
    height: 20,
  },
  {
    id: 'plantar_mediope_direito',
    label: 'Médio-pé direito',
    vista: 'plantar',
    x: 18,
    y: 49,
    width: 26,
    height: 22,
  },
  {
    id: 'plantar_mediope_esquerdo',
    label: 'Médio-pé esquerdo',
    vista: 'plantar',
    x: 56,
    y: 49,
    width: 26,
    height: 22,
  },
  {
    id: 'plantar_antepe_direito',
    label: 'Antepé direito',
    vista: 'plantar',
    x: 16,
    y: 69,
    width: 30,
    height: 16,
  },
  {
    id: 'plantar_antepe_esquerdo',
    label: 'Antepé esquerdo',
    vista: 'plantar',
    x: 54,
    y: 69,
    width: 30,
    height: 16,
  },
  {
    id: 'plantar_halux_direito',
    label: 'Hálux direito',
    vista: 'plantar',
    x: 38,
    y: 80,
    width: 9,
    height: 14,
  },
  {
    id: 'plantar_halux_esquerdo',
    label: 'Hálux esquerdo',
    vista: 'plantar',
    x: 53,
    y: 80,
    width: 9,
    height: 14,
  },
  {
    id: 'plantar_dedos_direito',
    label: 'Dedos do pé direito',
    vista: 'plantar',
    x: 15,
    y: 81,
    width: 30,
    height: 15,
  },
  {
    id: 'plantar_dedos_esquerdo',
    label: 'Dedos do pé esquerdo',
    vista: 'plantar',
    x: 55,
    y: 81,
    width: 30,
    height: 15,
  },
  {
    id: 'plantar_borda_lateral_direita',
    label: 'Borda lateral plantar direita',
    vista: 'plantar',
    x: 14,
    y: 42,
    width: 8,
    height: 40,
  },
  {
    id: 'plantar_borda_lateral_esquerda',
    label: 'Borda lateral plantar esquerda',
    vista: 'plantar',
    x: 78,
    y: 42,
    width: 8,
    height: 40,
  },
  {
    id: 'plantar_arco_medial_direito',
    label: 'Arco medial direito',
    vista: 'plantar',
    x: 34,
    y: 49,
    width: 10,
    height: 25,
  },
  {
    id: 'plantar_arco_medial_esquerdo',
    label: 'Arco medial esquerdo',
    vista: 'plantar',
    x: 56,
    y: 49,
    width: 10,
    height: 25,
  },
]

// ===== MAPEAMENTO VISUAL → CLÍNICO =====
export const MAPA_REGIAO_VISUAL_PARA_CLINICA: Record<string, string> = {
  frontal_coxa_direita: 'coxa_direita',
  frontal_coxa_esquerda: 'coxa_esquerda',
  frontal_joelho_direito: 'joelho_direito',
  frontal_joelho_esquerdo: 'joelho_esquerdo',
  frontal_perna_direita: 'panturrilha_direita',
  frontal_perna_esquerda: 'panturrilha_esquerda',
  frontal_tornozelo_direito: 'tornozelo_direito',
  frontal_tornozelo_esquerdo: 'tornozelo_esquerdo',
  frontal_maleolo_medial_direito: 'maleolo_medial_direito',
  frontal_maleolo_medial_esquerdo: 'maleolo_medial_esquerdo',
  frontal_dorso_pe_direito: 'dorso_pe_direito',
  frontal_dorso_pe_esquerdo: 'dorso_pe_esquerdo',
  frontal_halux_direito: 'halux_direito',
  frontal_halux_esquerdo: 'halux_esquerdo',
  frontal_trajeto_venoso_superficial_direito: 'trajeto_venoso_superficial_direito',
  frontal_trajeto_venoso_superficial_esquerdo: 'trajeto_venoso_superficial_esquerdo',

  posterior_coxa_direita: 'coxa_direita',
  posterior_coxa_esquerda: 'coxa_esquerda',
  posterior_fossa_poplitea_direita: 'regiao_poplitea_direita',
  posterior_fossa_poplitea_esquerda: 'regiao_poplitea_esquerda',
  posterior_panturrilha_direita: 'panturrilha_direita',
  posterior_panturrilha_esquerda: 'panturrilha_esquerda',
  posterior_tendao_calcaneo_direito: 'tornozelo_direito',
  posterior_tendao_calcaneo_esquerdo: 'tornozelo_esquerdo',
  posterior_tornozelo_direito: 'tornozelo_direito',
  posterior_tornozelo_esquerdo: 'tornozelo_esquerdo',
  posterior_calcaneo_direito: 'planta_pe_direito',
  posterior_calcaneo_esquerdo: 'planta_pe_esquerdo',
  posterior_planta_pe_direito: 'planta_pe_direito',
  posterior_planta_pe_esquerdo: 'planta_pe_esquerdo',
  posterior_trajeto_venoso_superficial_direito: 'trajeto_venoso_superficial_direito',
  posterior_trajeto_venoso_superficial_esquerdo: 'trajeto_venoso_superficial_esquerdo',

  // PLANTAR
  plantar_pe_direito: 'planta_pe_direito',
  plantar_pe_esquerdo: 'planta_pe_esquerdo',
  plantar_calcaneo_direito: 'planta_pe_direito',
  plantar_calcaneo_esquerdo: 'planta_pe_esquerdo',
  plantar_mediope_direito: 'planta_pe_direito',
  plantar_mediope_esquerdo: 'planta_pe_esquerdo',
  plantar_antepe_direito: 'planta_pe_direito',
  plantar_antepe_esquerdo: 'planta_pe_esquerdo',
  plantar_halux_direito: 'halux_direito',
  plantar_halux_esquerdo: 'halux_esquerdo',
  plantar_dedos_direito: 'planta_pe_direito',
  plantar_dedos_esquerdo: 'planta_pe_esquerdo',
  plantar_borda_lateral_direita: 'planta_pe_direito',
  plantar_borda_lateral_esquerda: 'planta_pe_esquerdo',
  plantar_arco_medial_direito: 'planta_pe_direito',
  plantar_arco_medial_esquerdo: 'planta_pe_esquerdo',
}

export function obterRegiaoClinicaDesdeVisual(regiaoVisualId: string): string | undefined {
  return MAPA_REGIAO_VISUAL_PARA_CLINICA[regiaoVisualId]
}

export function obterRegiaoVisualFrontal(id: string): RegiaoVisualMI | undefined {
  return REGIOES_FRONTAIS_MEMBROS_INFERIORES.find(r => r.id === id)
}

export function obterRegiaoVisualPosterior(id: string): RegiaoVisualMI | undefined {
  return REGIOES_POSTERIORES_MEMBROS_INFERIORES.find(r => r.id === id)
}

export function obterRegiaoVisualPlantar(id: string): RegiaoVisualMI | undefined {
  return REGIOES_BASE_PLANTAR_MEMBROS_INFERIORES.find(r => r.id === id)
}
