import { AcaoMembrosInferiores, PadraoMembrosInferiores, AchadoMembrosInferiores } from './types'

// Ações disponíveis para cada padrão
export const acoes: Record<PadraoMembrosInferiores, AcaoMembrosInferiores[]> = {
  normal: [
    {
      id: 'inspecao_geral',
      titulo: 'Inspeção geral',
      descricao: 'Avalia simetria, coloração e integridade',
      aba: 'inspecao',
      funcao: () => ({
        id: 'insp_normal',
        titulo: 'Inspeção geral',
        descricao: 'Membros inferiores simétricos, coloração normal, sem edema ou lesões.',
        categoria: 'inspecao',
      }),
    },
    {
      id: 'pulso_femoral_d',
      titulo: 'Pulso femoral direito',
      descricao: 'Palpa artéria femoral direita',
      aba: 'pulsos',
      funcao: () => ({
        id: 'pulso_fem_d',
        titulo: 'Pulso femoral direito',
        descricao: 'Pulso femoral direito: 2+/4 (normal)',
        categoria: 'pulsos',
        lado: 'direito',
      }),
    },
    {
      id: 'pulso_femoral_e',
      titulo: 'Pulso femoral esquerdo',
      descricao: 'Palpa artéria femoral esquerda',
      aba: 'pulsos',
      funcao: () => ({
        id: 'pulso_fem_e',
        titulo: 'Pulso femoral esquerdo',
        descricao: 'Pulso femoral esquerdo: 2+/4 (normal)',
        categoria: 'pulsos',
        lado: 'esquerdo',
      }),
    },
    {
      id: 'pulso_popliteo_d',
      titulo: 'Pulso poplíteo direito',
      descricao: 'Palpa artéria poplítea direita',
      aba: 'pulsos',
      funcao: () => ({
        id: 'pulso_pop_d',
        titulo: 'Pulso poplíteo direito',
        descricao: 'Pulso poplíteo direito: 2+/4 (normal)',
        categoria: 'pulsos',
        lado: 'direito',
      }),
    },
    {
      id: 'pulso_popliteo_e',
      titulo: 'Pulso poplíteo esquerdo',
      descricao: 'Palpa artéria poplítea esquerda',
      aba: 'pulsos',
      funcao: () => ({
        id: 'pulso_pop_e',
        titulo: 'Pulso poplíteo esquerdo',
        descricao: 'Pulso poplíteo esquerdo: 2+/4 (normal)',
        categoria: 'pulsos',
        lado: 'esquerdo',
      }),
    },
    {
      id: 'pulso_tibial_post_d',
      titulo: 'Pulso tibial posterior direito',
      descricao: 'Palpa artéria tibial posterior direita',
      aba: 'pulsos',
      funcao: () => ({
        id: 'pulso_tib_post_d',
        titulo: 'Pulso tibial posterior direito',
        descricao: 'Pulso tibial posterior direito: 2+/4 (normal)',
        categoria: 'pulsos',
        lado: 'direito',
      }),
    },
    {
      id: 'pulso_tibial_post_e',
      titulo: 'Pulso tibial posterior esquerdo',
      descricao: 'Palpa artéria tibial posterior esquerda',
      aba: 'pulsos',
      funcao: () => ({
        id: 'pulso_tib_post_e',
        titulo: 'Pulso tibial posterior esquerdo',
        descricao: 'Pulso tibial posterior esquerdo: 2+/4 (normal)',
        categoria: 'pulsos',
        lado: 'esquerdo',
      }),
    },
    {
      id: 'pulso_pedioso_d',
      titulo: 'Pulso pedioso direito',
      descricao: 'Palpa artéria pedíosa direita',
      aba: 'pulsos',
      funcao: () => ({
        id: 'pulso_ped_d',
        titulo: 'Pulso pedioso direito',
        descricao: 'Pulso pedioso direito: 2+/4 (normal)',
        categoria: 'pulsos',
        lado: 'direito',
      }),
    },
    {
      id: 'pulso_pedioso_e',
      titulo: 'Pulso pedioso esquerdo',
      descricao: 'Palpa artéria pedíosa esquerda',
      aba: 'pulsos',
      funcao: () => ({
        id: 'pulso_ped_e',
        titulo: 'Pulso pedioso esquerdo',
        descricao: 'Pulso pedioso esquerdo: 2+/4 (normal)',
        categoria: 'pulsos',
        lado: 'esquerdo',
      }),
    },
  ],
  daop: [
    {
      id: 'inspecao_geral',
      titulo: 'Inspeção geral',
      descricao: 'Avalia simetria, coloração e integridade',
      aba: 'inspecao',
      funcao: () => [
        {
          id: 'insp_daop_1',
          titulo: 'Coloração',
          descricao: 'Pé direito pálido em repouso, com tendência à rubescência ao pendente.',
          categoria: 'inspecao',
          lado: 'direito',
        },
        {
          id: 'insp_daop_2',
          titulo: 'Pele',
          descricao: 'Pele do membro inferior direito brilhante, sem pelos (rarefação).',
          categoria: 'inspecao',
          lado: 'direito',
        },
        {
          id: 'insp_daop_3',
          titulo: 'Temperatura',
          descricao: 'Pé direito frio em relação ao esquerdo.',
          categoria: 'inspecao',
          lado: 'direito',
        },
      ],
    },
    {
      id: 'prova_marcha',
      titulo: 'Prova da marcha',
      descricao: 'Avalia claudicação intermitente',
      aba: 'manobras',
      funcao: () => ({
        id: 'marcha_daop',
        titulo: 'Prova da marcha',
        descricao: 'Paciente interrompe marcha após ~80 metros por dor em panturrilha direita. Dor desaparece após 3-5 minutos de repouso. Compatível com claudicação intermitente.',
        categoria: 'manobras',
      }),
    },
    {
      id: 'isquemia_provocada',
      titulo: 'Manobra da isquemia provocada',
      descricao: 'Avalia resposta vascular à elevação e declive',
      aba: 'manobras',
      funcao: () => ({
        id: 'isquemia_daop',
        titulo: 'Manobra da isquemia provocada',
        descricao: 'À elevação: palidez plantar rápida (em <10 seg). Ao pendente: rubor lento de declive (>20 seg). Compatível com isquemia arterial.',
        categoria: 'manobras',
      }),
    },
    {
      id: 'pulso_femoral_d',
      titulo: 'Pulso femoral direito',
      descricao: 'Palpa artéria femoral direita',
      aba: 'pulsos',
      funcao: () => ({
        id: 'pulso_fem_d_daop',
        titulo: 'Pulso femoral direito',
        descricao: 'Pulso femoral direito: 2+/4 (presente)',
        categoria: 'pulsos',
        lado: 'direito',
      }),
    },
    {
      id: 'pulso_popliteo_d',
      titulo: 'Pulso poplíteo direito',
      descricao: 'Palpa artéria poplítea direita',
      aba: 'pulsos',
      funcao: () => ({
        id: 'pulso_pop_d_daop',
        titulo: 'Pulso poplíteo direito',
        descricao: 'Pulso poplíteo direito: 1+/4 (reduzido)',
        categoria: 'pulsos',
        lado: 'direito',
      }),
    },
    {
      id: 'pulso_tibial_post_d',
      titulo: 'Pulso tibial posterior direito',
      descricao: 'Palpa artéria tibial posterior direita',
      aba: 'pulsos',
      funcao: () => ({
        id: 'pulso_tib_post_d_daop',
        titulo: 'Pulso tibial posterior direito',
        descricao: 'Pulso tibial posterior direito: 0/4 (ausente)',
        categoria: 'pulsos',
        lado: 'direito',
      }),
    },
    {
      id: 'pulso_pedioso_d',
      titulo: 'Pulso pedioso direito',
      descricao: 'Palpa artéria pedíosa direita',
      aba: 'pulsos',
      funcao: () => ({
        id: 'pulso_ped_d_daop',
        titulo: 'Pulso pedioso direito',
        descricao: 'Pulso pedioso direito: 0/4 (ausente)',
        categoria: 'pulsos',
        lado: 'direito',
      }),
    },
    {
      id: 'itb',
      titulo: 'Índice tornozelo-braquial (ITB)',
      descricao: 'Calcula índice de perfusão',
      aba: 'medidas',
      funcao: () => [
        {
          id: 'itb_calculo_d',
          titulo: 'ITB direito',
          descricao: 'PAS tornozelo direito: 82 mmHg / PAS braquial: 140 mmHg = ITB 0,59 (sugestivo de DAOP moderada)',
          categoria: 'medidas',
          lado: 'direito',
        },
        {
          id: 'itb_calculo_e',
          titulo: 'ITB esquerdo',
          descricao: 'PAS tornozelo esquerdo: 138 mmHg / PAS braquial: 140 mmHg = ITB 0,99 (normal)',
          categoria: 'medidas',
          lado: 'esquerdo',
        },
      ],
    },
    {
      id: 'doppler_arterial',
      titulo: 'Solicitar Doppler arterial',
      descricao: 'Exame ultrassonográfico do fluxo arterial',
      aba: 'exames',
      funcao: () => ({
        id: 'doppler_art_daop',
        titulo: 'Doppler arterial',
        descricao: 'Fluxo arterial reduzido em artéria femoral superficial direita com padrão monofásico distal. Sugestivo de estenose/oclusão proximal.',
        categoria: 'exames',
      }),
    },
  ],
  tvp: [
    {
      id: 'inspecao_geral',
      titulo: 'Inspeção geral',
      descricao: 'Avalia simetria, coloração e integridade',
      aba: 'inspecao',
      funcao: () => ({
        id: 'insp_tvp',
        titulo: 'Inspeção',
        descricao: 'Edema unilateral em membro inferior direito. Panturrilha direita aumentada de volume.',
        categoria: 'inspecao',
        lado: 'direito',
      }),
    },
    {
      id: 'palpacao_panturrilha',
      titulo: 'Palpar panturrilhas',
      descricao: 'Avalia dor, aumento de volume e simetria',
      aba: 'inspecao',
      funcao: () => ({
        id: 'palp_panturrille_tvp',
        titulo: 'Palpação de panturrilhas',
        descricao: 'Panturrilha direita dolorosa à palpação profunda. Empastamento palpável. Diferença de circunferência: 4 cm.',
        categoria: 'palpacao',
        lado: 'direito',
      }),
    },
    {
      id: 'circunferencia_panturrilha',
      titulo: 'Medir circunferência das panturrilhas',
      descricao: 'Compara medidas entre os lados',
      aba: 'medidas',
      funcao: () => ({
        id: 'circ_tvp',
        titulo: 'Circunferência de panturrilhas',
        descricao: 'Panturrilha direita: 40 cm | Panturrilha esquerda: 36 cm | Diferença: 4 cm (sugestivo de TVP)',
        categoria: 'medidas',
      }),
    },
    {
      id: 'homans',
      titulo: 'Sinal de Homans',
      descricao: 'Dorsiflexão do pé causa dor em panturrilha',
      aba: 'manobras',
      funcao: () => ({
        id: 'homans_tvp',
        titulo: 'Sinal de Homans',
        descricao: 'Positivo: dor em panturrilha direita à dorsiflexão passiva do pé.',
        categoria: 'manobras',
        lado: 'direito',
      }),
    },
    {
      id: 'olow',
      titulo: 'Sinal de Olow',
      descricao: 'Dor ao palpar profundamente a panturrilha',
      aba: 'manobras',
      funcao: () => ({
        id: 'olow_tvp',
        titulo: 'Sinal de Olow',
        descricao: 'Positivo: dor significativa à palpação profunda de panturrilha direita.',
        categoria: 'manobras',
        lado: 'direito',
      }),
    },
    {
      id: 'bandeira',
      titulo: 'Sinal da Bandeira',
      descricao: 'Edema não deprimível com dedo',
      aba: 'manobras',
      funcao: () => ({
        id: 'bandeira_tvp',
        titulo: 'Sinal da Bandeira',
        descricao: 'Positivo: edema não deprimível após compressão digital.',
        categoria: 'manobras',
        lado: 'direito',
      }),
    },
    {
      id: 'doppler_venoso',
      titulo: 'Solicitar Doppler venoso',
      descricao: 'Ultrassom com compressibilidade venosa',
      aba: 'exames',
      funcao: () => ({
        id: 'doppler_ven_tvp',
        titulo: 'Doppler venoso',
        descricao: 'Veia poplítea direita não compressível com material ecogênico intraluminal. Compatível com trombose venosa profunda.',
        categoria: 'exames',
      }),
    },
  ],
  tep: [
    {
      id: 'inspecao_geral',
      titulo: 'Inspeção geral',
      descricao: 'Avalia simetria, coloração e integridade',
      aba: 'inspecao',
      funcao: () => ({
        id: 'insp_tep',
        titulo: 'Inspeção',
        descricao: 'Edema em membro inferior esquerdo. Possível trombose associada.',
        categoria: 'inspecao',
        lado: 'esquerdo',
      }),
    },
    {
      id: 'wells',
      titulo: 'Calcular escore de Wells para TEP',
      descricao: 'Avalia risco clínico de TEP',
      aba: 'medidas',
      funcao: () => ({
        id: 'wells_tep',
        titulo: 'Escore de Wells para TEP',
        descricao: 'Escore 6 pontos: edema unilateral + taquicardia + taquipneia. Risco intermediário de TEP.',
        categoria: 'medidas',
      }),
    },
    {
      id: 'd_dimero',
      titulo: 'Solicitar D-dímero',
      descricao: 'Teste de coagulação',
      aba: 'exames',
      funcao: () => ({
        id: 'd_dimero_tep',
        titulo: 'D-dímero',
        descricao: 'D-dímero: 1.850 ng/mL (elevado, acima de 500).',
        categoria: 'exames',
      }),
    },
    {
      id: 'angiotc_torax',
      titulo: 'Solicitar angio-TC de tórax',
      descricao: 'Tomografia com contraste das artérias pulmonares',
      aba: 'exames',
      funcao: () => ({
        id: 'angiotc_tep',
        titulo: 'Angio-TC de tórax',
        descricao: 'Falha de enchimento em ramo segmentar da artéria pulmonar direita compatível com embolia pulmonar segmentar.',
        categoria: 'exames',
      }),
    },
  ],
  insuficiencia_venosa: [
    {
      id: 'inspecao_geral',
      titulo: 'Inspeção geral',
      descricao: 'Avalia simetria, coloração e integridade',
      aba: 'inspecao',
      funcao: () => [
        {
          id: 'insp_iv_1',
          titulo: 'Varizes',
          descricao: 'Varizes visíveis em ambos os membros inferiores, mais acentuadas à esquerda.',
          categoria: 'inspecao',
          lado: 'bilateral',
        },
        {
          id: 'insp_iv_2',
          titulo: 'Dermatite ocre',
          descricao: 'Hiperpigmentação em região maleolar medial bilateral, sugestiva de dermatite ocre.',
          categoria: 'inspecao',
          lado: 'bilateral',
        },
        {
          id: 'insp_iv_3',
          titulo: 'Edema',
          descricao: 'Edema bilateral em tornozelos, pior ao final do dia.',
          categoria: 'inspecao',
          lado: 'bilateral',
        },
      ],
    },
    {
      id: 'circunferencia_panturrilha',
      titulo: 'Medir circunferência das panturrilhas',
      descricao: 'Compara medidas entre os lados',
      aba: 'medidas',
      funcao: () => ({
        id: 'circ_iv',
        titulo: 'Circunferência de panturrilhas',
        descricao: 'Panturrilha direita: 38 cm | Panturrilha esquerda: 39 cm | Diferença: 1 cm (simétrico, consistente com IVC)',
        categoria: 'medidas',
      }),
    },
    {
      id: 'homans',
      titulo: 'Sinal de Homans',
      descricao: 'Dorsiflexão do pé causa dor em panturrilha',
      aba: 'manobras',
      funcao: () => ({
        id: 'homans_iv',
        titulo: 'Sinal de Homans',
        descricao: 'Negativo: sem dor à dorsiflexão passiva.',
        categoria: 'manobras',
      }),
    },
  ],
  ulcera_arterial: [
    {
      id: 'inspecao_geral',
      titulo: 'Inspeção geral',
      descricao: 'Avalia simetria, coloração e integridade',
      aba: 'inspecao',
      funcao: () => [
        {
          id: 'insp_ua_1',
          titulo: 'Localização da lesão',
          descricao: 'Úlcera no dorso do pé direito, em região distal.',
          categoria: 'inspecao',
          lado: 'direito',
        },
        {
          id: 'insp_ua_2',
          titulo: 'Aspecto da lesão',
          descricao: 'Bordas regulares e bem definidas. Fundo pálido ou necrótico. Sem exsudato importante.',
          categoria: 'inspecao',
          lado: 'direito',
        },
        {
          id: 'insp_ua_3',
          titulo: 'Pele adjacente',
          descricao: 'Pele brilhante, fria, sem pelos ao redor. Rarefação de pelos em membro.',
          categoria: 'inspecao',
          lado: 'direito',
        },
      ],
    },
    {
      id: 'pulso_pedioso_d',
      titulo: 'Pulso pedioso direito',
      descricao: 'Palpa artéria pedíosa direita',
      aba: 'pulsos',
      funcao: () => ({
        id: 'pulso_ped_d_ua',
        titulo: 'Pulso pedioso direito',
        descricao: 'Pulso pedioso direito: 0/4 (ausente)',
        categoria: 'pulsos',
        lado: 'direito',
      }),
    },
    {
      id: 'itb',
      titulo: 'Índice tornozelo-braquial (ITB)',
      descricao: 'Calcula índice de perfusão',
      aba: 'medidas',
      funcao: () => ({
        id: 'itb_ua',
        titulo: 'ITB direito',
        descricao: 'PAS tornozelo direito: 65 mmHg / PAS braquial: 135 mmHg = ITB 0,48 (compatível com isquemia arterial grave)',
        categoria: 'medidas',
        lado: 'direito',
      }),
    },
    {
      id: 'doppler_arterial',
      titulo: 'Solicitar Doppler arterial',
      descricao: 'Exame ultrassonográfico do fluxo arterial',
      aba: 'exames',
      funcao: () => ({
        id: 'doppler_art_ua',
        titulo: 'Doppler arterial',
        descricao: 'Oclusão de artéria tibial anterior direita. Fluxo reduzido em artérias tibial posterior e fibular.',
        categoria: 'exames',
      }),
    },
  ],
  ulcera_venosa: [
    {
      id: 'inspecao_geral',
      titulo: 'Inspeção geral',
      descricao: 'Avalia simetria, coloração e integridade',
      aba: 'inspecao',
      funcao: () => [
        {
          id: 'insp_uv_1',
          titulo: 'Localização da lesão',
          descricao: 'Úlcera em região maleolar medial esquerda.',
          categoria: 'inspecao',
          lado: 'esquerdo',
        },
        {
          id: 'insp_uv_2',
          titulo: 'Aspecto da lesão',
          descricao: 'Bordas irregulares. Fundo com exsudato amarelado. Teciduração presente.',
          categoria: 'inspecao',
          lado: 'esquerdo',
        },
        {
          id: 'insp_uv_3',
          titulo: 'Sinais associados',
          descricao: 'Dermatite ocre ao redor. Varizes visíveis. Edema bilateral simétrico.',
          categoria: 'inspecao',
          lado: 'bilateral',
        },
      ],
    },
    {
      id: 'circunferencia_panturrilha',
      titulo: 'Medir circunferência das panturrilhas',
      descricao: 'Compara medidas entre os lados',
      aba: 'medidas',
      funcao: () => ({
        id: 'circ_uv',
        titulo: 'Circunferência de panturrilhas',
        descricao: 'Panturrilha direita: 36 cm | Panturrilha esquerda: 38 cm | Diferença: 2 cm',
        categoria: 'medidas',
      }),
    },
    {
      id: 'homans',
      titulo: 'Sinal de Homans',
      descricao: 'Dorsiflexão do pé causa dor em panturrilha',
      aba: 'manobras',
      funcao: () => ({
        id: 'homans_uv',
        titulo: 'Sinal de Homans',
        descricao: 'Negativo: sem dor à dorsiflexão passiva.',
        categoria: 'manobras',
      }),
    },
    {
      id: 'pulso_femoral_e',
      titulo: 'Pulso femoral esquerdo',
      descricao: 'Palpa artéria femoral esquerda',
      aba: 'pulsos',
      funcao: () => ({
        id: 'pulso_fem_e_uv',
        titulo: 'Pulso femoral esquerdo',
        descricao: 'Pulso femoral esquerdo: 2+/4 (normal)',
        categoria: 'pulsos',
        lado: 'esquerdo',
      }),
    },
  ],
}

// Função auxiliar para obter ações de um padrão
export function obterAcoes(padrao: PadraoMembrosInferiores): AcaoMembrosInferiores[] {
  return acoes[padrao] || acoes.normal
}
